"""Writes touch_calibration.h: a Touch controller factory calibration in Constellation's JSON format (the Rift S /
Quest "TrackedObject" document). The emulator's controllers are posed by injection, so the IMU is ideal and the LED
ring is a plausible circle; Constellation only has to accept the document.
Usage: python3 touch_calibration.py [override.json]   (also writes the JSON there, for a no-rebuild test)"""
import json, math, sys

LEDS = 22   # Touch ring


def document():
    points = {}
    for i in range(LEDS):
        a = 2 * math.pi * i / LEDS
        n = (math.cos(a), 0.0, math.sin(a))
        points[f"Point{i}"] = [0.045 * n[0], 0.02, 0.045 * n[2], n[0], n[1], n[2], 0.0, 0.0, 0.0]
    ident = [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0]   # 3x3 rectification then offset
    return {"TrackedObject": {
        "JsonVersion": 2,
        "FlexVersion": 1,
        "ImuPosition": [0.0, 0.0, 0.0],
        "AccCalibration": ident,
        "GyroCalibration": ident,
        "ModelPoints": points,
        "Lensing": {"Model0": [1.0, 0.0, 0.0, 0.0, 0.0]},
    }}


if __name__ == "__main__":
    text = json.dumps(document(), separators=(",", ":"))
    with open(__file__.replace(".py", ".h"), "w") as f:
        f.write("// generated by touch_calibration.py\n#pragma once\nstatic const char TOUCH_JSON[] = R\"json(%s)json\";\n" % text)
    if len(sys.argv) > 1:
        open(sys.argv[1], "w").write(text)
